--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : Mar 29 2015 12:58
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'Rav'   
-- RAVID           :  ID of Rav 
-- Name            :  Name of Rav
-- Address         :  Address where Rav lives
-- Phone           :  Rav's phone number
-- DateOfBirth     :  Rav's date of birth
-- BankAccountNum  :  Rav's back account for payments
--
CREATE TABLE Rav (
    RAVID          NUMBER(38) NOT NULL,
    RavName        VARCHAR2(38) NOT NULL,
    Address        VARCHAR2(38) NOT NULL,
    Phone          VARCHAR2(38),
    DateOfBirth    DATE NOT NULL,
    BankAccountNum NUMBER(38) NOT NULL,
CONSTRAINT pk_Rav PRIMARY KEY (RAVID));


--
-- Create Table    : 'Book'   
-- BOOKID          :  ID of book
-- Name            :  book's title
-- Author          :  book's author
-- Category        :  book's category
-- Abstract        :  book's abstract
-- Publisher      :  book's publisher
-- ShelfNum        :  book's shelf number
-- PubYear         :  book's publishing year
--
CREATE TABLE Book (
    BOOKID         NUMBER(38) NOT NULL,
    Name           VARCHAR2(38) NOT NULL,
    Author         VARCHAR2(38),
    Category       VARCHAR2(38),
    Abstract       VARCHAR2(256),
    Publisher      VARCHAR2(38),
    ShelfNum       NUMBER(38) NOT NULL,
    PubYear        NUMBER(4),
CONSTRAINT pk_Book PRIMARY KEY (BOOKID))
;



--
-- Create Table    : 'VolunteerGroup'   
-- VGID            :  Volunteer group ID
-- Address         :  where voluteer happens
-- DayOfWeek       :  day of volunteer activity
-- TimeOfDay       :  time of volunteer activity
-- Organization    :  organization providing activity
-- Details         :  details of activity
-- Phone           :  phone number of activity mananger
--
CREATE TABLE VolunteerGroup (
    VGID           NUMBER(38) NOT NULL,
    Address        VARCHAR2(38),
    DayOfWeek      NUMBER(38) NOT NULL,
    TimeOfDay      TIMESTAMP NOT NULL,
    Organization   VARCHAR2(38),
    Details        VARCHAR2(256),
    Phone          VARCHAR2(12),
CONSTRAINT pk_VolunteerGroup PRIMARY KEY (VGID))
;


--
-- Create Table    : 'BeitMidrashHall'   
-- BMHID           :  beit midrash ID
-- Address         :  address of beit midrash
-- Name            :  name of beit midrash
-- Capacity        :  max number of students in hall
-- WomenSection    :  is there a women section for prayers
-- TorahBooksNum   :  number of torah books in beit midrash
-- RAVID           :  (references Rav.RAVID) head of beit midrash
--
CREATE TABLE BeitMidrashHall (
    BMHID          NUMBER(38) NOT NULL,
    Address        VARCHAR2(38) NOT NULL,
    Name           VARCHAR2(38) NOT NULL,
    Capacity       NUMBER(38) NOT NULL,
    WomenSection   CHAR(1) NOT NULL,
    TorahBooksNum  NUMBER(38) NOT NULL,
    RAVID          NUMBER(38) NOT NULL,
CONSTRAINT pk_BeitMidrashHall PRIMARY KEY (BMHID),
CONSTRAINT fk_BeitMidrashHall FOREIGN KEY (RAVID)
    REFERENCES Rav (RAVID)
    ON DELETE CASCADE)
;


--
-- Create Table    : 'Placed'   
-- BMHID           :  (references BeitMidrashHall.BMHID)
-- BOOKID          :  (references Book.BOOKID)
--
CREATE TABLE Placed (
    BMHID          NUMBER(38) NOT NULL,
    BOOKID         NUMBER(38) NOT NULL,
CONSTRAINT pk_Placed PRIMARY KEY (BMHID,BOOKID),
CONSTRAINT fk_Placed FOREIGN KEY (BMHID)
    REFERENCES BeitMidrashHall (BMHID)
    ON DELETE CASCADE,
CONSTRAINT fk_Placed2 FOREIGN KEY (BOOKID)
    REFERENCES Book (BOOKID))
;


--
-- Create Table    : 'Teaches'   
-- BOOKID          :  (references Book.BOOKID)
-- RAVID           :  (references Rav.RAVID)
--
CREATE TABLE Teaches (
    BOOKID         NUMBER(38) NOT NULL,
    RAVID          NUMBER(38) NOT NULL,
CONSTRAINT pk_Teaches PRIMARY KEY (BOOKID,RAVID),
CONSTRAINT fk_Teaches FOREIGN KEY (BOOKID)
    REFERENCES Book (BOOKID)
    ON DELETE CASCADE,
CONSTRAINT fk_Teaches2 FOREIGN KEY (RAVID)
    REFERENCES Rav (RAVID))
;


--
-- Create Table    : 'Student'   
-- STDID           :  ID of student
-- Name            :  student's name
-- Address         :  address where student lives
-- Phone           :  student's phone number
-- Class           :  Class where student gets leasons from his Rav
-- DateOfBirth     :  student's date of birth
-- RAVID           :  (references Rav.RAVID)
-- BMHID           :  (references BeitMidrashHall.BMHID)
-- VGID            :  (references VolunteerGroup.VGID)
--
CREATE TABLE Student (
    STDID          NUMBER(38) NOT NULL,
    Name           VARCHAR2(38) NOT NULL,
    Address        VARCHAR2(38) NOT NULL,
    Phone          VARCHAR2(12),
    Class          VARCHAR2(38),
    DateOfBirth    DATE NOT NULL,
    RAVID          NUMBER(38) NOT NULL,
    BMHID          NUMBER(38) NOT NULL,
    VGID           NUMBER(38) NOT NULL,
CONSTRAINT pk_Student PRIMARY KEY (STDID),
CONSTRAINT fk_Student FOREIGN KEY (RAVID)
    REFERENCES Rav (RAVID)
    ON DELETE CASCADE,
CONSTRAINT fk_Student2 FOREIGN KEY (BMHID)
    REFERENCES BeitMidrashHall (BMHID)
    ON DELETE CASCADE,
CONSTRAINT fk_Student3 FOREIGN KEY (VGID)
    REFERENCES VolunteerGroup (VGID)
    ON DELETE CASCADE)
;


--
-- Create Table    : 'Studies'   
-- BOOKID          :  (references Book.BOOKID)
-- STDID           :  (references Student.STDID)
--
CREATE TABLE Studies (
    BOOKID         NUMBER(38) NOT NULL,
    STDID          NUMBER(38) NOT NULL,
CONSTRAINT pk_Studies PRIMARY KEY (BOOKID,STDID),
CONSTRAINT fk_Studies FOREIGN KEY (BOOKID)
    REFERENCES Book (BOOKID)
    ON DELETE CASCADE,
CONSTRAINT fk_Studies2 FOREIGN KEY (STDID)
    REFERENCES Student (STDID))
;
